version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nishchaynode
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      runas: root
    - location: scripts/start_server.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: root
